#!/bin/bash

alias c='clear'
alias C='clear && printf "\e[3J"'

alias g='git'
alias ls='ls -GFh'

alias fucking='sudo'

alias npmlist='npm list -g --depth=0'

alias hideDesktopFiles='defaults write com.apple.finder CreateDesktop -bool false && killall Finder'
alias showDesktopFiles='defaults write com.apple.finder CreateDesktop -bool true && killall Finder'
alias showAllFiles='defaults write com.apple.finder AppleShowAllFiles YES'
alias hideAllFiles='defaults write com.apple.finder AppleShowAllFiles YES'

alias watch="fswatch -0 -o . | xargs -n1 -I {} "
alias ddd='rm -rf ~/Library/Developer/Xcode/DerivedData/*'

alias tpbcopy='tmux saveb - | pbcopy'
alias start_sp='cd ~/Documents/elixir/silver_post; ~/dotFiles/tmux/sp.sh'
alias qvi="~/dotFiles/vimanywhere.sh"

